# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v6.0.2
      id: stale
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        days-before-stale: 1
        days-before-delete: 2
        comment-updates: false
        max-issues: 20
        tag-committer: false
        stale-branch-label: 'stale branch 🗑️'
        compare-branches: 'info'
        branches-filter-regex: '^((?!main|develop|master))'
        rate-limit: false
        pr-check: false
        dry-run: true
        ignore-issue-interaction: false
    - name: print output
      run: |
        echo ${{ steps.stale.outputs.stale-branches}}
